site_name: Visual Quiz Builder
site_url: https://af1a1.github.io/
site_author: Aflal Ahamed

theme:
  name: material
  features:
    - instant
    - tabs
  palette:
    primary: white
    accent: black
  font:
    text: Arimo
    code: Fira Code
  logo: logo.png
  favicon: favicon.ico


# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

plugins:
  - search # necessary for search to work
  # - git-revision-date-localized
  # - mkdocs-git-committers-plugin
  # - mkdocs-git-revision-date-localized

extra_css:
  - stylesheets/extra.css
